<?php


return [
    [
        'event_id' => 'event_6606b4be5509c',
        'event_name' => 'งานแสดงสินค้าและบริการ 2024',
        'categories' => '1,2,3',
        'contact_email' => 'admin@admin.com',
        'contact_phone' => '0812345678',
        'facebook' => 'facebook.com',
        'twitter' => 'twitter.com',
        'instagram' => 'instagram.com',
        'line' => 'line',
        'website' => 'website',
        'event_time' => 'specific',
        'date_start' => '2024-05-01 00:00:00',
        'date_end' => '2024-05-03 00:00:00',
        'time_start' => '08:38:00',
        'time_end' => '09:39:00',
        'venue' => 'venue',
        'event_location' => 'ชั้น 3 ศูนย์การค้า แอ ม พาร์ ค จุฬา ที่ อยู่ 353 ซอย จุฬาฯ 5 Khwaeng Wang Mai, Pathum Wan, Krung Thep Maha Nakhon 10330, Thailand',
        'placename' => 'ศูนย์การค้า แอ ม พาร์ ค จุฬา',
        'travel_info' => 'เดินทางมาจากสถานีรถไฟฟ้าบีทีเอส สถานีชิดลม ใช้เวลาเดินทางประมาณ 10 นาที',
        'room' => '7',
        'lat' => 13.740135457763378,
        'lng' => 100.52460193634033,
        'event_phase' => 'Initial',
        'event_status' => 'Draft',
        'is_specific_date' => 1,
        'is_online' => 0,
        'is_deleted' => 0,
        'age_require' => 0,
        'limit_participant' => 300,
        'limit_staff' => 100,
        'thumbnail' => '564000009297002.jpg',
        'banner_image' => '564000009297002.jpg',
        'content' => include(database_path('seeders/contentMock.php')),
        'banner_text_bg' => '#000000',
        'banner_text_color' => '#fff',
        'content-theme' => 'light',
        'created_at' => '2024-03-29 12:31:58',
        'updated_at' => '2024-03-29 12:47:22',
    ],
    [
        'event_name' => 'GAZILLION BUBBLE SHOW',
        'categories' => '8,9',
        'event_time' => 'specific',
        'date_start' => '2024-06-01 00:00:00',
        'date_end' => '2024-06-03 00:00:00',
        'time_start' => '17:00:00',
        'time_end' => '20:00:00',
        'venue' => 'online',
        'event_phase' => 'Initial',
        'event_status' => 'Draft',
        'is_specific_date' => 1,
        'is_online' => 1,
        'is_deleted' => 0,
        'content' => '<p>การแสดงโชว์เกี่ยวกับฟองอากาศ หรือบับเบิ้ลอย่างยื่งใหญ่ตระการตา จัดโดย เมืองไทยรัชดาลัย เธียเตอร์</p>',
    ],
    [
        'event_name' => 'IVE THE1ST WORLD TOUR <SHOW WHAT I HAVE> IN BANGKOK',
        'categories' => '10',
        'event_time' => 'specific',
        'date_start' => '2024-05-10 00:00:00',
        'date_end' => '2024-5-12 00:00:00',
        'time_start' => '17:30:00',
        'time_end' => '21:30:00',
        'venue' => 'online',
        'event_phase' => 'Initial',
        'event_status' => 'Draft',
        'is_specific_date' => 1,
        'is_online' => 1,
        'is_deleted' => 0,
        'content' => '<p>การแสดงโชว์ ร้องเพลงและเต้น K-pop</p>',
    ],
    [
        'event_name' => '4EVE Concert “NOW OR NEVER” Live at Impact Arena',
        'categories' => '10',
        'event_time' => 'specific',
        'date_start' => '2024-7-10 00:00:00',
        'date_end' => '2024-7-10 00:00:00',
        'time_start' => '18:30:00',
        'time_end' => '22:00:00',
        'venue' => 'online',
        'event_phase' => 'Initial',
        'event_status' => 'Draft',
        'is_specific_date' => 1,
        'is_online' => 1,
        'is_deleted' => 0,
        'content' => '<p>การแสดงโชว์ ร้องเพลงและเต้น T-pop องค์กร XOXO Entertainment</p>',
    ],
    [
        'event_name' => 'Pride Cruise Bangkok',
        'categories' => '10',
        'event_time' => 'specific',
        'date_start' => '2024-2-3 00:00:00',
        'date_end' => '2024-2-3 00:00:00',
        'time_start' => '17:00:00',
        'time_end' => '23:30:00',
        'venue' => 'online',
        'event_phase' => 'Initial',
        'event_status' => 'Draft',
        'is_specific_date' => 1,
        'is_online' => 1,
        'is_deleted' => 0,
        'content' => '<p>เป็นงานแข่งขันที่จัดขึ้นในกรุงเทพฯ ประเทศไทย โดยเน้นในเรื่องของความหลากหลายทางเพศและการยอมรับตนเอง งานนี้มักจะมีการแสดงโชว์และกิจกรรมที่เกี่ยวข้องกับสังคม LGBTQ+ รวมถึงการเดินเรือเป็นที่โปรดปรานของผู้เข้าร่วม โดยงานนี้มักจะดำเนินการในช่วงเดือนพฤษภาคมของทุกปี และมักจะเป็นหนึ่งในเหตุการณ์ที่ท่องเที่ยวที่น่าตื่นเต้นในกรุงเทพฯ</p>',
    ],
    [
        'event_name' => 'สัมมนาเทคโนโลยีสารสนเทศแห่งชาติ 2024',
        'categories' => '2,4',
        'event_time' => 'specific',
        'date_start' => '2024-08-15 00:00:00',
        'date_end' => '2024-08-17 00:00:00',
        'time_start' => '09:00:00',
        'time_end' => '17:00:00',
        'venue' => 'online',
        'event_phase' => 'Initial',
        'is_specific_date' => 1,
        'is_online' => 0,
        'is_deleted' => 0,
        'content' => '<p>สัมมนาเทคโนโลยีสารสนเทศแห่งชาติ ครั้งที่ 28 จัดขึ้นเพื่อเสนอและแลกเปลี่ยนความรู้ในด้านเทคโนโลยีสารสนเทศระดับชาติและนานาชาติ มีการนำเสนอเรื่องราวทางวิชาการ ผลงานวิจัย และนวัตกรรมที่เกี่ยวข้อง รวมถึงการจัดสรรงบประมาณในการพัฒนาสารสนเทศและเทคโนโลยีสารสนเทศในประเทศไทย</p>',
    ],
    [
        'event_name' => 'งานแสดงเทคโนโลยี CES (Consumer Electronics Show) 2024',
        'categories' => '2,8',
        'event_time' => 'specific',
        'date_start' => '2024-01-05 00:00:00',
        'date_end' => '2024-01-08 00:00:00',
        'time_start' => '00:00:00',
        'time_end' => '00:00:00',
        'venue' => 'online',
        'event_phase' => 'Initial',
        'is_specific_date' => 1,
        'is_online' => 0,
        'is_deleted' => 0,
        'content' => '<p>เน้นเป็นแพลตฟอร์มสำหรับการนำเสนอเทคโนโลยีใหม่ๆ และนวัตกรรมที่เกี่ยวข้องกับอุตสาหกรรมอิเล็กทรอนิกส์และไอที</p>',
    ],
    [
        'event_name' => 'Google I/O 2024',
        'categories' => '2,8',
        'event_time' => 'announce_after',
        'date_start' => '1970-01-01 00:00:00',
        'date_end' => '1970-01-01 00:00:00',
        'time_start' => '00:00:00',
        'time_end' => '00:00:00',
        'venue' => 'online',
        'event_phase' => 'Initial',
        'is_specific_date' => 1,
        'is_online' => 0,
        'is_deleted' => 0,
        'content' => '<p>เป็นงานประชุมทางเทคโนโลยีที่จัดขึ้นโดย Google ซึ่งมักมีการประกาศเทคโนโลยีและนวัตกรรมใหม่ๆ ของบริษัท</p>',
    ],
    [
        'event_name' => 'Mobile World Congress (MWC) 2024',
        'categories' => '2,8',
        'event_time' => 'announce_after',
        'date_start' => '2024-03-26 00:00:00',
        'date_end' => '2024-04-01 00:00:00',
        'time_start' => '00:00:00',
        'time_end' => '00:00:00',
        'venue' => 'online',
        'event_phase' => 'Initial',
        'is_specific_date' => 1,
        'is_online' => 0,
        'is_deleted' => 0,
        'content' => '<p>เป็นงานแสดงสินค้าและเทคโนโลยีที่เกี่ยวข้องกับโทรศัพท์มือถือและอุปกรณ์เครือข่ายมือถือ</p>',
    ],

    [
        'event_name' => 'Apple WWDC (Worldwide Developers Conference) 2024',
        'categories' => '2,8',
        'event_time' => 'announce_after',
        'date_start' => '2024-06-1 00:00:00',
        'date_end' => '2024-06-01 00:00:00',
        'time_start' => '00:00:00',
        'time_end' => '00:00:00',
        'venue' => 'online',
        'event_phase' => 'Initial',
        'is_specific_date' => 1,
        'is_online' => 0,
        'is_deleted' => 0,
        'content' => '<p>เป็นงานประชุมที่จัดขึ้นโดย Apple เพื่อประกาศเทคโนโลยีและแพลตฟอร์มใหม่ ๆ แก่นักพัฒนา</p>',
    ],

    [
        'event_name' => 'Amazon re:MARS 2024',
        'categories' => '2,8',
        'event_time' => 'announce_after',
        'date_start' => '1970-01-01 00:00:00',
        'date_end' => '1970-01-01 00:00:00',
        'time_start' => '00:00:00',
        'time_end' => '00:00:00',
        'venue' => 'online',
        'event_phase' => 'Initial',
        'is_specific_date' => 1,
        'is_online' => 0,
        'is_deleted' => 0,
        'content' => '<p>เป็นงานประชุมเทคโนโลยีของ Amazon ที่เน้นในด้านการเรียนรู้เชิงปฏิบัติและนวัตกรรมทางเทคโนโลยีในหลายด้าน เช่น หุ่นยนต์ ปัญญาประดิษฐ์ และพลังงานสุขภาพของมนุษย์</p>',
    ],

];
